### ISSUE TITLE
Crash on Load. Help me.

### ISSUE THREAD

**Issue by CaioSimioni** [Eianex/Freshly-Distant#1]
![image](https://github.com/user-attachments/assets/5b7ea1a7-f3cd-4478-9e73-ce5cafb46afc)
version: 1.0.2

**Comment by Eianex** [comment]
PrismLauncher or any other Launchers different of Modrinth are a rabbit hole. This modpack works on Modrinth, I recommend using it to fix the error. If not, I dont know how to fix this particular issue tbh.
